apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy: {}
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: onkarpatole28/my-app-2
        ports:
        - containerPort: 3000
        name: my-app-2
        resources: {}
status: {}
